Repository googleapis/python-videointelligence, pull requests merged in 2020-10, with the labels that each got.

#6 tests: normalize VPCSC config in systests
  tests/system.py
  tests/system/test_system.py
  tests/system/test_vpcsc.py
Labels: api: videointelligence, automerge, cla: yes, type: process

#53 feat(v1): add PersonDetection and FaceDetection
  google/cloud/videointelligence_v1/gapic/enums.py
  google/cloud/videointelligence_v1/gapic/video_intelligence_service_client.py
  google/cloud/videointelligence_v1/gapic/video_intelligence_service_client_config.py
  google/cloud/videointelligence_v1/proto/video_intelligence.proto
  google/cloud/videointelligence_v1/proto/video_intelligence_pb2.py
  google/cloud/videointelligence_v1/proto/video_intelligence_pb2_grpc.py
  google/cloud/videointelligence_v1beta2/gapic/video_intelligence_service_client_config.py
  google/cloud/videointelligence_v1beta2/proto/video_intelligence_pb2.py
  google/cloud/videointelligence_v1beta2/proto/video_intelligence_pb2_grpc.py
  google/cloud/videointelligence_v1p1beta1/gapic/video_intelligence_service_client_config.py
  google/cloud/videointelligence_v1p1beta1/proto/video_intelligence_pb2.py
  google/cloud/videointelligence_v1p1beta1/proto/video_intelligence_pb2_grpc.py
  google/cloud/videointelligence_v1p2beta1/gapic/video_intelligence_service_client_config.py
  google/cloud/videointelligence_v1p2beta1/proto/video_intelligence_pb2.py
  google/cloud/videointelligence_v1p2beta1/proto/video_intelligence_pb2_grpc.py
  google/cloud/videointelligence_v1p3beta1/gapic/streaming_video_intelligence_service_client_config.py
  google/cloud/videointelligence_v1p3beta1/gapic/video_intelligence_service_client_config.py
  google/cloud/videointelligence_v1p3beta1/proto/video_intelligence_pb2.py
  google/cloud/videointelligence_v1p3beta1/proto/video_intelligence_pb2_grpc.py
  noxfile.py
  synth.metadata
Labels: automerge, cla: yes, context: none

#58 chore: flaky detect_faces tests in beta
  samples/analyze/video_detect_faces_beta_test.py
  samples/analyze/video_detect_faces_gcs_beta_test.py
Labels: cla: yes

#49 docs: add samples from video/cloud-client/labels
  .kokoro/samples/python3.6/common.cfg
  .kokoro/samples/python3.7/common.cfg
  .kokoro/samples/python3.8/common.cfg
  noxfile.py
  samples/labels/README.rst
  samples/labels/README.rst.in
  samples/labels/labels.py
  samples/labels/labels_test.py
  samples/labels/noxfile.py
  samples/labels/requirements-test.txt
  samples/labels/requirements.txt
  synth.metadata
Labels: api: videointelligence, cla: yes, samples

#62 samples: fixed flaky test on vision beta samples
  samples/analyze/beta_snippets_test.py
Labels: cla: yes

#66 chore: fixed flaky test by adding retry
  samples/analyze/beta_snippets_test.py
Labels: cla: yes

#69 test: fix system tests for VPCSC
  tests/system/test_system.py
  tests/system/test_vpcsc.py
Labels: automerge, cla: yes
