Repository googleapis/python-videointelligence, pull requests merged in 2021-04, with the labels that each got.

#127 samples: updates face recognition to v1
  samples/analyze/noxfile.py
  samples/analyze/requirements.txt
  samples/analyze/video_detect_faces.py
  samples/analyze/video_detect_faces_gcs.py
  samples/analyze/video_detect_faces_gcs_test.py
  samples/analyze/video_detect_faces_test.py
Labels: api: videointelligence, cla: yes, samples

#129 chore: add license headers
  .pre-commit-config.yaml
  docs/conf.py
  google/cloud/videointelligence_v1p3beta1/__init__.py
  samples/analyze/noxfile.py
  synth.metadata
Labels: api: videointelligence, cla: yes, context: partial

#133 chore: prevent normalization of semver versioning
  setup.py
Labels: api: videointelligence, automerge, cla: yes

#134 chore(revert): revert preventing normalization
  setup.py
Labels: api: videointelligence, automerge, cla: yes

#131 chore: Refactor test
  samples/analyze/analyze_test.py
Labels: api: videointelligence, cla: yes
