Repository googleapis/python-videointelligence, pull requests merged in 2021-09, with the labels that each got.

#210 chore(samples): drop obsolete samples
  samples/analyze/beta_snippets.py
  samples/analyze/beta_snippets_test.py
Labels: api: videointelligence, cla: yes, automerge

#214 chore: reference main branch of google-cloud-python
  README.rst
Labels: api: videointelligence, cla: yes

#215 samples: add streaming_automl_action_recognition sample
  samples/analyze/beta_snippets.py
  samples/analyze/beta_snippets_test.py
Labels: api: videointelligence, cla: yes, automerge, samples

#221 chore: relocate owl bot post processor
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
Labels: api: videointelligence, cla: yes, automerge
