Repository googleapis/python-videointelligence, pull requests merged in 2021-05, with the labels that each got.

#135 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .github/header-checker-lint.yml
  .kokoro/release.sh
  .kokoro/release/common.cfg
  docs/_static/custom.css
  owlbot.py
  renovate.json
  samples/analyze/noxfile.py
  samples/labels/noxfile.py
  samples/quickstart/noxfile.py
  samples/shotchange/noxfile.py
  synth.metadata
Labels: api: videointelligence, automerge, cla: yes

#141 chore: add library type to .repo-metadata.json
  .repo-metadata.json
Labels: api: videointelligence, cla: yes

#152 chore: increased timeout by 200s to reduce flakiness
  samples/analyze/beta_snippets.py
Labels: api: videointelligence, automerge, cla: yes

#143 samples: add streaming_automl_object_tracking sample
  samples/analyze/beta_snippets.py
  samples/analyze/beta_snippets_test.py
Labels: api: videointelligence, cla: yes, samples

#154 fix(deps): add packaging requirement
  setup.py
  testing/constraints-3.6.txt
Labels: api: videointelligence, automerge, cla: yes
